theme: jekyll-theme-slate
title: "くりえなページ"
theme: 
twitter:
  username: crystalenergy
defaults:
  - scope:
      path: ""
    values:
      image:
        path: /img/logo.jpg
        height: 630
        width: 1200
